//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app_HackSpace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cricketer
    {
        public int ID { get; set; }
        public string Name_ { get; set; }
        public string FullName { get; set; }
        public Nullable<int> Age { get; set; }
        public string Team { get; set; }
        public Nullable<int> OdiRuns { get; set; }
        public Nullable<int> TestRuns { get; set; }
        public Nullable<int> Century { get; set; }
        public Nullable<int> HalfCentury { get; set; }
        public Nullable<int> Wickets { get; set; }
        public Nullable<int> Catches { get; set; }
        public bool IsSelected { get; set; }
    }
}
