//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app_HackSpace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expert
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Expert()
        {
            this.has_expert = new HashSet<has_expert>();
        }
    
        public int idExpert { get; set; }
        public string expertise { get; set; }
        public string availabilities { get; set; }
        public string bio { get; set; }
        public string hourly_rate { get; set; }
        public int id_Profile { get; set; }
        public bool IsSelected { get; set; }
    
        public virtual C_Profile C_Profile { get; set; }
        public virtual C_Profile C_Profile1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<has_expert> has_expert { get; set; }
    }
}
