//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app_HackSpace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facilitator
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Facilitator()
        {
            this.Hackathons = new HashSet<Hackathon>();
            this.Hackathons1 = new HashSet<Hackathon>();
        }
    
        public int idFacilitator { get; set; }
        public string availabilities { get; set; }
        public string bio { get; set; }
        public string hourly_rate { get; set; }
        public string website { get; set; }
        public string urlFcb { get; set; }
        public string urlTwit { get; set; }
        public string urlLin { get; set; }
        public int id_Profile { get; set; }
        public bool IsSelected { get; set; }
    
        public virtual C_Profile C_Profile { get; set; }
        public virtual C_Profile C_Profile1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hackathon> Hackathons { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Hackathon> Hackathons1 { get; set; }
    }
}
