//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app_HackSpace.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HackSpaceDBEntities : DbContext
    {
        public HackSpaceDBEntities()
            : base("name=HackSpaceDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C_Partner> C_Partner { get; set; }
        public virtual DbSet<Expert> Experts { get; set; }
        public virtual DbSet<Facilitator> Facilitators { get; set; }
        public virtual DbSet<Goodie> Goodies { get; set; }
        public virtual DbSet<Hackathon> Hackathons { get; set; }
        public virtual DbSet<has_expert> has_expert { get; set; }
        public virtual DbSet<has_goodie> has_goodie { get; set; }
        public virtual DbSet<has_participant> has_participant { get; set; }
        public virtual DbSet<has_reward> has_reward { get; set; }
        public virtual DbSet<has_sponsor> has_sponsor { get; set; }
        public virtual DbSet<Jury> Juries { get; set; }
        public virtual DbSet<Location_> Location_ { get; set; }
        public virtual DbSet<Participant> Participants { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Program> Programs { get; set; }
        public virtual DbSet<Reward> Rewards { get; set; }
        public virtual DbSet<Sponsor> Sponsors { get; set; }
        public virtual DbSet<Super_hero> Super_hero { get; set; }
        public virtual DbSet<Theme> Themes { get; set; }
        public virtual DbSet<C_Profile> C_Profile { get; set; }
        public virtual DbSet<C_Type> C_Type { get; set; }
        public virtual DbSet<Food_pref> Food_pref { get; set; }
        public virtual DbSet<has_skills> has_skills { get; set; }
        public virtual DbSet<Size_tshirt> Size_tshirt { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<Deliver> Delivers { get; set; }
        public virtual DbSet<Explore> Explores { get; set; }
        public virtual DbSet<Launch> Launches { get; set; }
        public virtual DbSet<Pitch> Pitches { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
    }
}
