//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app_HackSpace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class has_sponsor
    {
        public int idhas_sponsor { get; set; }
        public int idHackathon { get; set; }
        public int idSponsor { get; set; }
    
        public virtual Hackathon Hackathon { get; set; }
        public virtual Sponsor Sponsor { get; set; }
    }
}
