//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace app_HackSpace.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sponsor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sponsor()
        {
            this.has_sponsor = new HashSet<has_sponsor>();
        }
    
        public int idSponsor { get; set; }
        public string logo { get; set; }
        public string max_budget { get; set; }
        public string prefer_thematic { get; set; }
        public string needs { get; set; }
        public int id_Profile { get; set; }
        public bool IsSelected { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<has_sponsor> has_sponsor { get; set; }
        public virtual C_Profile C_Profile { get; set; }
        public virtual C_Profile C_Profile1 { get; set; }
    }
}
